install libpng12

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,2 +1,62 @@
-#!/usr/bin/env bash
-echo "-----> [Bla Bla Bla Bla]"
+#!/bin/bash
+
+indent() {
+  sed -u 's/^/       /'
+}
+
+echo "-----> Install libpng"
+
+BUILD_DIR=$1
+CACHE_DIR=$2
+VENDOR_DIR="$BUILD_DIR/vendor"
+INSTALL_DIR="$VENDOR_DIR/libpng"
+CACHE_FILE="$CACHE_DIR/libpng.tar.gz"
+
+
+if [ ! -f $CACHE_FILE ]; then
+  # install libpng
+  LIBPNG_FILE="libpng-1.2.59.tar.gz"
+  LIBPNG_DIR="libpng-1.2.59"
+  # SSL cert used on libpng not recognized by heroku.
+  LIBPNG_URL="http://iweb.dl.sourceforge.net/project/libpng/libpng12/1.2.59/libpng-1.2.59.tar.gz"
+
+  echo "-----> Downloading libpng from $LIBPNG_URL"
+  wget $LIBPNG_URL -P $BUILD_DIR | indent
+
+  echo "-----> Extracting libpng from $BUILD_DIR/$LIBPNG_FILE"
+  if [ ! -f $BUILD_DIR/$LIBPNG_FILE ]; then
+    echo "Error: Unable to download libpng" | indent
+    ls $BUILD_DIR | indent
+    exit 1;
+  fi
+  tar xvf $BUILD_DIR/$LIBPNG_FILE | indent
+
+  echo "-----> Building libpng"
+  cd $LIBPNG_DIR
+  export CPPFLAGS="-I$INSTALL_DIR/include"
+  export LDFLAGS="-L$INSTALL_DIR/lib"
+  ./configure --prefix=$INSTALL_DIR
+  make && make install
+  cd ..
+  rm -rf $LIBPNG_DIR
+
+  # cache for future deploys
+  echo "-----> Caching libpng installation"
+  cd $VENDOR_DIR
+  REL_INSTALL_DIR="libpng"
+  tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
+  mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
+
+else
+  # cache exists, extract it
+  echo "-----> Extracting libpng $CACHE_FILE => $VENDOR_DIR"
+  tar xzf $CACHE_FILE -C $VENDOR_DIR
+fi
+
+# update PATH and LD_LIBRARY_PATH
+echo "-----> Updating environment variables"
+PROFILE_PATH="$BUILD_DIR/.profile.d/libpng.sh"
+ACTUAL_INSTALL_PATH="$HOME/vendor/libpng"
+mkdir -p $(dirname $PROFILE_PATH)
+echo "export PATH=$ACTUAL_INSTALL_PATH/bin:\$PATH" >> $PROFILE_PATH
+echo "export LD_LIBRARY_PATH=$ACTUAL_INSTALL_PATH/lib:\$LD_LIBRARY_PATH" >> $PROFILE_PATH
